"""Add images_count column to Car

Revision ID: 17eb4ffe67d1
Revises: 62f78f6634e8
Create Date: 2025-05-31 12:07:51.264834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17eb4ffe67d1'
down_revision: Union[str, None] = '62f78f6634e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('images_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'images_count')
    # ### end Alembic commands ###
