"""Changed Colum name tittle to title

Revision ID: 4126b79ba81b
Revises: 17eb4ffe67d1
Create Date: 2025-05-31 13:50:58.436359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4126b79ba81b'
down_revision: Union[str, None] = '17eb4ffe67d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('cars', 'tittle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('tittle', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cars', 'title')
    # ### end Alembic commands ###
